name: phidi
version: 0.1.0.0
description: Please see the README on GitHub at <https://github.com/birthevdb/Type_Inference_PHiDI/inference#readme>
github: "birthevdb/Type_Inference_PHiDI/inference"
category: Language
author: Birthe van den Berg
maintainer: birthe.vandenberg@kuleuven.be
copyright: 2020, Birthe van den Berg
license: BSD3
dependencies:
  - base >=4.7 && <5
  - mtl
  - haskeline
  - array
  - containers
  - protolude >= 0.2
  - text
  - filepath
  - directory
  - megaparsec >= 6.0
  - scientific
  - prettyprinter
  - repline
  - QuickCheck

ghc-options:
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-name-shadowing
  - -fwarn-incomplete-patterns

library:
  source-dirs: src
  exposed-modules:
    - PHiDI.Parser.Parser
    - PHiDI.Environment
    - PHiDI.Operators
    - PHiDI.PrettyPrint
    - PHiDI.Source.Syntax
    - PHiDI.Source.Subtyping
    - PHiDI.Source.Inference
    - PHiDI.Source.Desugar
    - PHiDI.Target.Syntax
    - PHiDI.Target.Eval
    - PHiDI.Util
    - PHiDI.Translations
    - PHiDI.Test
    - PHiDI
  dependencies:
    - unbound-generics

executables:
  phidi-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - phidi

tests:
  phidi-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tasty >=0.11.1
      - tasty-hspec >=1.1.3.1
      - phidi
